### PR TITLE
Corrected the selector for GMGridViewCell.ctor(CGRect frame)

### PR DESCRIPTION
**Pull request by Cybrosys**
Corrected the selector for GMGridViewCell.ctor(CGRect frame) so that it matches UICollectionViewCell.

### CODE REVIEW

**Comment by Cybrosys** [comment]
Bitrise?

I forgot to update the version number in AssemblyInfo.cs. It would be great if you could create a updated NuGet package with the pull request.

It's causing a build error: https://bugzilla.xamarin.com/show_bug.cgi?id=42184

**Comment by roycornelissen** [comment]
Not sure why BitRise failed, but I'll make a new Nuget

**Comment by roycornelissen** [comment]
Thanks!
Bitrise was failing because my workflow was apparently outdated. I updated the steps and now it runs fine :)
Thanks for the fix! I see you have other issues open. If I find time I'll work on them but if you have fixes for them, feel free to send a PR. I'd love the help.
Version 0.0.9 should be up on Nuget now.
Kind regards, Roy

Date: Thu, 7 Jul 2016 01:05:14 -0700

**Comment by Cybrosys** [comment]
Thanks and sure. Sent another PR for the status bar miscoloring when navigating.

I was hoping to fix the translucency stuff as well but I'm not familiar enough with what everything does at the moment. I can see that the Navbar.Translucent is set to true, as per default, but it makes no difference. 

Maybe the GMImagePickerController.SetupNavigationController isn't doing things properly or the GMGridViewController is getting Inset so it's never behind the NavigationBar.

**Pull request merged**
