### PR TITLE
Review and update of pt translations.

### PR DESCRIPTION
**Pull request by BrenoBaronte**
Hi! I reviewed and corrected some portuguese translations. I hope that helps you.

### CODE REVIEW

**Comment by roycornelissen** [comment]
Hi @BrenoBaronte, thank you! Indeed it helps me a lot. Thanks for your time and effort. One request... Recently two new keys were added that are not in the Portuguese file, would you mind adding them with the correct translation too?

They are:

```
/* Accessibility voiceover hint for image selection cursor */
"picker.accessibility.check-to-select" = "Check to select the image";

/* Accessibility voiceover hint for image deselection cursor */
"picker.accessibility.uncheck-to-deselect" = "Uncheck to deselect the image"; 
```

These are accessibility hints which are spoken by voice-over when enabled.

Thanks!

**Comment by roycornelissen** [comment]
Fixes #42

**Comment by BrenoBaronte** [comment]
Hi @roycornelissen, I added the two news keys that you requested!

**Comment by roycornelissen** [comment]
Awesome, thank you! I’m merging this one and I’ll release it in a few days, along with some small other changes. Cheers!

**Pull request merged**
